### ISSUE TITLE
Provide a new release

### ISSUE THREAD

**Issue by hmaack** [ffaker/ffaker#472]
# release candidate

The last release is from august 2020, is it time for a new release? Check the list of commits to get an impression about what has been changed. https://github.com/ffaker/ffaker/compare/v2.17.0...main

# tasks

- [ ] update CHANGELOG.md
- [ ] build gem
- [ ] install gem locally and check functionality at least in 2 ruby versions
- [ ] provide it to rubygems
- [ ] have a beer 🍻

**Comment by hmaack** [comment]
any opinion @marocchino @Volosh1n thumbs up?

**Comment by Volosh1n** [comment]
Sure. We had even small releases, but now there are plenty of changes since august. Let's do it
